twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/public/css': styles

        '%kernel.project_dir%/public/images': images

    form_themes: [
        'bootstrap_5_layout.html.twig'
        ]

    globals:
        picture_directory: '%app.pictures%'

        entityFaker: '@App\Service\EntityFakerService'

when@test:
    twig:
        strict_variables: true
